# Generated by Django 5.0.3 on 2025-11-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=2500)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
