# Generated by Django 5.0.3 on 2025-11-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_blogpostcategory_alter_blogpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcategory',
            name='slug',
        ),
    ]
