# Generated by Django 5.2.7 on 2026-03-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_blogpost_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.DeleteModel(
            name='BlogPostCategory',
        ),
    ]
